### ISSUE TITLE
Small issue at 21:30

### ISSUE THREAD

**Issue by thebarefootboy** [UbhiTS/ad-alexatalkingclock#1]
I use this when working late in my office so have it announcing every half hour until 23:30. 

I noticed that at 21:30 it repeated the 21:00 message - very simple fix by changing line 102 to

      elif hour == 21 and minute == 0:

Thanks for a great app I'm amazed at how useful it is :)

**Comment by UbhiTS** [comment]
Wow, thanks. You are officially my first app beta tester :) ... i'll fix the code and update you soon ! thanks for pointing this bug out !

**Comment by UbhiTS** [comment]
I've just released v1.0.1 with this issue fixed. I've verified at my end and everything looks smooth. Can you please verify at your end as well before I can close this issue. Thanks!

**Comment by thebarefootboy** [comment]
Sweet improvement to the code  it makes the start and end times truly user definable now - all working as it should. 

Only thing I would suggest is an update to the description as it states "...every half hour (politely) from 7 AM to 9 PM..." 

Thanks for creating and updating - I'm a Python guy but new to appdaemon on HA so your app is my intro to the possibilities! 😃

**Comment by UbhiTS** [comment]
using home assistant, it was my first shot at python. I'm a C# .Net guy by career but totally hooked on to python now ever since I started writing the AppDaemon apps. Thanks for your time and your inputs, truly appreciate it :)
