### ISSUE TITLE
TypeError: 'NoneType' object is not iterable.

### ISSUE THREAD

**Issue by joemadd3n** [UbhiTS/ad-alexatalkingclock#12]
The AlexaTalkingClock has suddenly stopped working, AppDaemon reports this, any ideas?

`2020-07-16 08:00:00.028310 WARNING alexa_talking_clock: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 766, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/ad-alexatalkingclock/apps/alexa_talking_clock/alexa_talking_clock.py", line 169, in time_announce
    time_speech = self.get_time_speech(now)
  File "/config/appdaemon/apps/ad-alexatalkingclock/apps/alexa_talking_clock/alexa_talking_clock.py", line 230, in get_time_speech
    for reminder in self.reminders:
TypeError: 'NoneType' object is not iterable`

**Comment by UbhiTS** [comment]
Try updating to the latest version of HA, and HassIO. If the problem still persists, please let me know and we can debug this together.

**Comment by UbhiTS** [comment]
Oh, and by the way, you have to update your apps.yaml config if you've recently updated the Alexa Talking Clock:

alexa_talking_clock:
  module: alexa_talking_clock
  class: AlexaTalkingClock
  alexas:
    - media_player.kitchen_alexa
    - media_player.upper_big_bedroom_alexa
  announcements:
    bell: true  # for SONOS, set to False
    start_time: "07:30:00"
    end_time: "21:30:00"
    half_hour: true
    quarter_hour: true
    default_speech: "It's {time}." # {day} {date} {time} 
  voice: # for SONOS, remove this section
    volume_offset: 0 # -40 to 4, default 0
    pitch_offset: 0 # -33 to 50, default 0
    rate: 100 # 20 to 250, default 100
    whisper: false
  reminders: 
    # daily
    - schedule: "daily, 07:30:00" 
      reminder: "Good morning. Today is {day}, {date}, and it's {time}."
    - schedule: "daily, 12:00:00"
      reminder: "Good afternoon. Today is {day}, {date}, and it's {time}."
    - schedule: "daily, 17:00:00"
      reminder: "Good evening. It's {time}."
    - schedule: "daily, 21:30:00"
      reminder: "It's {time}. Good night. And sweet dreams."
    # weekdays
    - schedule: "weekdays, 09:30:00"
      reminder: "It's {time}. Quick reminder. Did you go to gym today?"
    # weekends
    - schedule: "weekends, 09:30:00"
      reminder: "It's {time}. Question. Are you planning to go for a run or a hike today?"
    # mon, tue, wed, thu, fri, sat, sun
    - schedule: "tue, 21:00:00"
      reminder: "It's {time}. Quick Reminder. Did you take out the garbage?"
    - schedule: "wed, 09:30:00"
      reminder: "It's {time}. What day is it? It's Hump Day! Yaaaay!"
    - schedule: "fri, 04:30:00"
      reminder: "The weekend is almost here. Better plan it now, or lose it forever!"
  debug: false

**Comment by joemadd3n** [comment]
Thanks @UbhiTS 
Just to confirm the following;

Running the latest Supervisor 229
on Home Assistant 0.112.4 (latest)
with AppDaemon 4 (Current version: 0.2.6)

My apps.yaml has the following config entry;

`alexa_talking_clock:
  module: alexa_talking_clock
  class: AlexaTalkingClock
  alexas:
    - media_player.office_echo_dot
    - media_player.kitchen_echo_dot
  announcements:
    bell: true # for SONOS, set to False
    start_time: "08:00:00"
    end_time: "17:00:00"
    half_hour: true
    quarter_hour: false
    default_speech: "It's {time}."
  voice: # for SONOS, remove this section
    volume_offset: -5 # -40 to 4, default 0
    pitch_offset: 0 # -33 to 50, default 0
    rate: 100 # 20 to 250, default 100
    whisper: false
  debug: false`

**Comment by UbhiTS** [comment]
I've just updated the code so if there are not reminders in the config, it will not throw an error. Can you please reinstall but in the version dropdown, select the master version and see if that works. Once you confirm, I will release a new version.

**Comment by joemadd3n** [comment]
> I've just updated the code. If there are no reminders in the config, it will not throw an error anymore. Can you please reinstall but in the version dropdown, select the master version and see if that works. Once you confirm, I will release a new version.

Thank you! That seems to have resolved the issue!

**Comment by UbhiTS** [comment]
thank you. releasing a new version :)
