### ISSUE TITLE
Unable to get the time because of service.

### ISSUE THREAD

**Issue by blindndangerous** [UbhiTS/ad-alexatalkingclock#13]
Hello,
Just found this app, and thought I'd give it a try.  However, after installing the media player and setting up your app, I see the following in my logs.  This also happens with the doorbell app as well.
2020-10-16 03:17:50.085689 INFO alexa_talking_clock: TIME_ANNOUNCE It's 3:17 AM.: master_bedroom
2020-10-16 03:17:50.078789 WARNING AppDaemon: Unknown service (default/notify/alexa_media) in call_service from alexa_talking_clock
When I look at services under dev tools, I see notify.alexa_media, as well as notify.alexa_media_my speaker name.  I thought it might be adding
notify:
  - platform: alexa_media
    name: alexa_media
to configuration.yaml but no luck.  I'm sure it's an easy fix but I can't figure out what could be causing it.  Thought I'd done everything correctly.
Thanks for any help.
I'd like to use this with Sonos, and have already set bell to false in apps.yaml.

**Comment by UbhiTS** [comment]
can we do a remote debug on your machine?

**Comment by blindndangerous** [comment]
I ended up getting this working (well the doorbell part) through automations. Going to close this.  Thanks.
