### ISSUE TITLE
multiple media players

### ISSUE THREAD

**Issue by charliedgabriel** [UbhiTS/ad-alexatalkingclock#2]
is it possible to add multiple media players to announce the time and at different times? is so, how? thanks you for this great application. gets me up in time to go to work. love it.

thanks

**Comment by UbhiTS** [comment]
you can add multiple app.yaml entries like below
`
alexa_talking_clock_kitchen:
  module: alexa_talking_clock
  class: AlexaTalkingClock
  alexa: media_player.kitchen_alexa
  start_hour: 7
  start_minute: 0
  end_hour: 21
  end_minute: 0
  announce_hour: true
  announce_half_hour: true
  announce_quarter_hour: false

alexa_talking_clock_living_room:
  module: alexa_talking_clock
  class: AlexaTalkingClock
  alexa: media_player.living_room_alexa
  start_hour: 9
  start_minute: 0
  end_hour: 17
  end_minute: 0
  announce_hour: true
  announce_half_hour: true
  announce_quarter_hour: false
`

**Comment by UbhiTS** [comment]
Can you please let me know if this is what you were looking for ? I will close this issue once you reply. Thanks
