### ISSUE TITLE
Can't get this working with Sonos speaker

### ISSUE THREAD

**Issue by 5and0** [UbhiTS/ad-alexatalkingclock#3]
Hi, I am targeting the associated media_player entity that the Alexa Media Player integration has found, I can send tts to this using the notifier service, but unfortunately I don't get announcements from the talking clock :'( 

This has worked for me with an echo show device

**Comment by UbhiTS** [comment]
I'll have to modify the app to use the Sonos Service specifically. Right now I use the notify/alexa service on the speech call. Let me see how I can modify that to use sonos, i'll have to lookup the Sonos service to call. Give me a couple of days, i'll try to fix it up !

**Comment by UbhiTS** [comment]
I don't have a sonos player so debugging will be a bit difficult though. Or if you are already using Sonos Text to Speech and you could send me the service to call, that would be awesome !

**Comment by UbhiTS** [comment]
Or, if we could do a live remote debug session, that would work too :)

**Comment by UbhiTS** [comment]
Hi, any updates ... were you able to make this work on Sonos ? if not, can we have a live session so I can debug and find a way to TTS to Sonos :)

**Comment by 5and0** [comment]
Apologies for the delayed response... The following works fine for the Alexa media entity that is discovered for the speaker ... 
![image](https://user-images.githubusercontent.com/46394702/79080035-f7204200-7d55-11ea-9e4c-758c0659150d.png)

**Comment by UbhiTS** [comment]
Can we do a live debug session so that I can see what setting works in AppDaemon. Technically speaking, if I just replace the notify/alexa call with notify/alexa_media_david_s_sonos_one that should work. But I just want to confirm before I modify my code. Let me know. Thanks

**Comment by UbhiTS** [comment]
@5and0 can we please do a live debug so that once I can test your config, I will release a general feature on it

**Comment by 5and0** [comment]
'bell: false' = winner

The issue appears is that the Sonos speaker won't accept a 'type: announce' message. The easiest way to avoid this, when I took time to have a look closely at your code was to turn off the bell feature. 

Thank you again for coming back to me, and keep up the great work !

**Comment by UbhiTS** [comment]
Awesome ! that's so great you found out the fix. I'll close this issue and make a note in the readme and definitely credit you for this. Thank you so much :)
