### ISSUE TITLE
Configuring Alexa talking CLock

### ISSUE THREAD

**Issue by Sajivve** [UbhiTS/ad-alexatalkingclock#4]
Hi Tarun

Have been struggling with configuring Alexa Talking Clock sice a week but havent been able to make it speak.

Here is my directory structure.

Am i doing something wrong?

Is some reference to be ,made in configuration.yaml?

Please help.

Regards
Sajive Trehan
Zurich - Switzerland

![Screenshot 2020-04-05 11 47 18](https://user-images
![Screenshot 2020-04-05 11 50 38](https://user-images.githubusercontent.com/47938878/78471724-c035a500-7733-11ea-895e-025927b8cb6d.png)
.githubusercontent.com/47938878/78471680-6503b280-7733-11ea-8259-00e6c8fdd16b.png)

**Comment by UbhiTS** [comment]
Hi Sajive, Try changing the end hour to 23 maybe.
otherwise the config looks fine.
if it doesnt work, maybe we can have a live debug session if you are free sometime ?


________________________________

**Comment by UbhiTS** [comment]
Also, you need to install the Alexa Media Player plugin as a prerequisite. Make sure you've done that.

**Comment by Sajivve** [comment]
Dear Tarun

Thanks for your messages.

I changed the values it doesnt work.

Alexa Media Player is installed and configured and is working.

I will appreciate your live help.

I live in Zurich - Switzerland and am available whenever you have time.

I await your update.


Vielen Dank für Ihre Kenntnisnahme
Freundliche Grüsse


TREHAN Sajive

***********************************************
Schaffhauserstrasse 60
CH 8302 Kloten
Schweiz

Fone : + 41 44 516 74 74
Natel : + 41 76 674 60 09
Email : sajivve.trehaan@gmail.com
***********************************************
Haftungsausschluss:
Diese Nachricht ist nur für den Empfänger gedacht.
Sollte es von Unbefugten entgegengenommen werden, bitte ich Sie, mich so bald wie möglich persönlich zu benachrichtigen
und dann die Kommunikation mit allen Anhängen sowie Kopien zu vernichten oder zu löschen. Die Verwendung der Informationen ist untersagt.

**Comment by Sajivve** [comment]
Sehr geehrter Herr Tarun


I am still waiting for your answer to my Request for live help.

Please advise.


Vielen Dank für Ihre Kenntnisnahme
Freundliche Grüsse


TREHAN Sajive

***********************************************
Schaffhauserstrasse 60
CH 8302 Kloten
Schweiz

Fone : + 41 44 516 74 74
Natel : + 41 76 674 60 09
Email : sajivve.trehaan@gmail.com
***********************************************
Haftungsausschluss:
Diese Nachricht ist nur für den Empfänger gedacht.
Sollte es von Unbefugten entgegengenommen werden, bitte ich Sie, mich so bald wie möglich persönlich zu benachrichtigen
und dann die Kommunikation mit allen Anhängen sowie Kopien zu vernichten oder zu löschen. Die Verwendung der Informationen ist untersagt.

**Comment by UbhiTS** [comment]
problem solved. It was an appdaemon 4 configuration issue. all the best with ESP8266 :)
