### ISSUE TITLE
Whisper Mode and Volume Control

### ISSUE THREAD

**Issue by Sajivve** [UbhiTS/ad-alexatalkingclock#7]
Hello Tarun

Thanks for the wonderful support and the Lovely Alexa Talking Clock.

I have configured it on 4 Alexa Devices and it works perfectly.

Just needed two small features:

1. Ability to control the volume on a per device basis (in case of multiple devices).
2. Ability to set Whisper Mode on a per device basis (in case of multiple devices).

Please keep me updated.

Regards
Sajive

**Comment by UbhiTS** [comment]
Hi Sajivve, please can you take the master version and test the app. I've made changes and also added 5 new controls to configure whisper, rate, volume, pitch as well as the bell before time time.
Let me know how it goes. Once you test and confirm, I'll release a new version.

**Comment by UbhiTS** [comment]
released v1.0.5

for different modes and volumes for different alexas, use multiple apps.yaml configuration entries

**Comment by Sajivve** [comment]
Sehr geehrter Tarun


Thanks for your email.

I can only change the Volume offset and NOT the volume itself.

Can you please guide me on how to customise the volume?


Vielen Dank für Ihre Kenntnisnahme
Freundliche Grüsse


TREHAN Sajive

***********************************************
Schaffhauserstrasse 60
CH 8302 Kloten
Schweiz

Fone : + 41 44 516 74 74
Natel : + 41 76 674 60 09
Email : sajivve.trehaan@gmail.com
***********************************************
Haftungsausschluss:
Diese Nachricht ist nur für den Empfänger gedacht.
Sollte es von Unbefugten entgegengenommen werden, bitte ich Sie, mich so bald wie möglich persönlich zu benachrichtigen
und dann die Kommunikation mit allen Anhängen sowie Kopien zu vernichten oder zu löschen. Die Verwendung der Informationen ist untersagt.

**Comment by UbhiTS** [comment]
I dont understand your use case, can you please explain in detail your requirement. There is an option to change the volume for a device, but I would rather not tinker with that.

**Comment by Sajivve** [comment]
Sehr geehrter Tarun


The use case is:

I have one Alexa Flex on the door for notifications etc exclusively.

This plays various notifications at various volume levels say door bell notification through Alexa Media Player is played at Volume 10 and then say take medicine notification is played at volume 5. This volume I control through Alexa Media player Volume Set commands.

However say if the door bell rang at 958 am at volume 10 then the Talking clock at 10 am is at Volume 10 too which I want to be always at 5 Volume and after 8pm to 11 pm on Whisper for which I use a separate instance.

Hope I was able to express the problem.

I await your update.


Vielen Dank für Ihre Kenntnisnahme
Freundliche Grüsse


TREHAN Sajive

***********************************************
Schaffhauserstrasse 60
CH 8302 Kloten
Schweiz

Fone : + 41 44 516 74 74
Natel : + 41 76 674 60 09
Email : sajivve.trehaan@gmail.com
***********************************************
Haftungsausschluss:
Diese Nachricht ist nur für den Empfänger gedacht.
Sollte es von Unbefugten entgegengenommen werden, bitte ich Sie, mich so bald wie möglich persönlich zu benachrichtigen
und dann die Kommunikation mit allen Anhängen sowie Kopien zu vernichten oder zu löschen. Die Verwendung der Informationen ist untersagt.

**Comment by UbhiTS** [comment]
You do the volume_offset to -20 or -25 for that ? it will keep the original alexa volume, but the announcement it will play at half the volume

**Comment by ik0adr** [comment]
Hi and thanks, I use this from months and is very nice.
Just a question: would it be easy to accomodate for different languages? 
I just inserted the italian phrases into the file, and works, but a more universal approach would be nice.
E.g.
`    if hour == self.start_hour and minute == self.start_minute and hour <= 11:
      prefix = "Buongiorno."
    elif hour == 12 and minute == 0:
      prefix = "Buom pomeriggio."
    elif hour == 17 and minute == 0:
      prefix = "Buonasera."
    elif hour == self.end_hour and minute == self.end_minute and hour >= 20:
      postfix = "Buonanotte. E dolci sogni."

    hour = hour - 12 if hour > 12 else hour

    if minute == 0:
      time_speech = f"Sono le {hour} {ampm_str}."
    else:
      time_speech = f"Sono le {hour}:{minute:02d} {ampm_str}."

    return prefix + " " + time_speech + " " + postfix
`

**Comment by UbhiTS** [comment]
> ## Hi and thanks, I use this from months and is very nice.
> Just a question: would it be easy to accomodate for different languages?
> I just inserted the italian phrases into the file, and works, but a more universal approach would be nice.
> E.g.
> ```
> if hour == self.start_hour and minute == self.start_minute and hour <= 11:
>   prefix = "Buongiorno."
> elif hour == 12 and minute == 0:
>   prefix = "Buom pomeriggio."
> elif hour == 17 and minute == 0:
>   prefix = "Buonasera."
> elif hour == self.end_hour and minute == self.end_minute and hour >= 20:
>   postfix = "Buonanotte. E dolci sogni."
> 
> hour = hour - 12 if hour > 12 else hour
> 
> if minute == 0:
>   time_speech = f"Sono le {hour} {ampm_str}."
> else:
>   time_speech = f"Sono le {hour}:{minute:02d} {ampm_str}."
> 
> return prefix + " " + time_speech + " " + postfix
> ```

created a new feature request. https://github.com/UbhiTS/ad-alexatalkingclock/issues/9
will try to get to in soon :) ... thanks for your encouragement !

**Comment by UbhiTS** [comment]
> You can do the volume_offset to -20 or -25 for that ? it will keep the original alexa volume, but the announcement it will play at half the volume

Hey Sajivve, did this workaround work for you ?

**Comment by joselito11** [comment]
How to get alexa to announce at volume 10?
